[package]
name = "native-viewer"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
glam.workspace = true
pollster = "0.4"
mw-core = { path = "../../crates/mw-core" }
mw-async-data = { path = "../../crates/mw-async-data" }
mw-provider-mvt = { path = "../../crates/mw-provider-mvt" }
mw-render-wgpu = { path = "../../crates/mw-render-wgpu" }
mw-telemetry = { path = "../../crates/mw-telemetry" }
log.workspace = true
wgpu.workspace = true
winit = "0.30"
instant = "0.1"
[target.'cfg(target_arch = "wasm32")'.dependencies]
instant = { version = "0.1", features = [ "wasm-bindgen" ] }